# Generated by Django 5.0.1 on 2024-02-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
