// userConstants.js

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

// Add new constants for change password
export const USER_SEND_CHANGE_PASSWORD_REQUEST = 'USER_SEND_CHANGE_PASSWORD_REQUEST';
export const USER_SEND_CHANGE_PASSWORD_SUCCESS = 'USER_SEND_CHANGE_PASSWORD_SUCCESS';
export const USER_SEND_CHANGE_PASSWORD_FAIL = 'USER_SEND_CHANGE_PASSWORD_FAIL';

export const USER_CONFIRM_CHANGE_PASSWORD_REQUEST = 'USER_CONFIRM_CHANGE_PASSWORD_REQUEST';
export const USER_CONFIRM_CHANGE_PASSWORD_SUCCESS = 'USER_CONFIRM_CHANGE_PASSWORD_SUCCESS';
export const USER_CONFIRM_CHANGE_PASSWORD_FAIL = 'USER_CONFIRM_CHANGE_PASSWORD_FAIL';
